/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.victormadu.github.rectangle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class OblongRectangleTest {
    @Test
    void rectangeTest() {
        var rectange = new OblongRectangle(5, 5);
        assertEquals(25, rectange.area());
        assertEquals(5, rectange.length());
        assertEquals(5, rectange.width());
    }
}
