/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.victormadu.github.circle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ConcentricCircleTest {

    @Test
    void circleProperties() {
        var circle = new ConcentricCircle(7);
        assertEquals(154, circle.area(), 0.1);
        assertEquals(44, circle.perimeter(), 0.1);
        assertEquals(7, circle.raidus());
    }
}
