/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.victormadu.github.circle;

import io.victormadu.github.geometry.Circle;

public final class ConcentricCircle implements Circle {
    private final double radius;

    public ConcentricCircle(double radius) {
        if (radius < 0) {
            throw new IllegalArgumentException("Radius cannot be negative");
        }
        this.radius = radius;
    }

    @Override
    public double area() {
        return Math.PI * radius * radius;
    }

    @Override
    public double raidus() {
        return radius;
    }

    @Override
    public double perimeter() {
        return 2 * Math.PI * radius;
    }
}
