name: Publish Java Package

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release
    types:
      - closed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if PR was merged
        if: github.event.pull_request.merged == true
        run: echo "This PR was merged, running the build."

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build and publish
        run: ./gradlew publish
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
